name: CI
on:
    push:
        branches:
        - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install essensial
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata
          sudo apt-get install -y --no-install-recommends curl build-essential clang libboost-all-dev python3 python3-pip libc6 libncurses5 libstdc++6 wget
          wget -O gcc_arm_embedded.tar.bz2 "https://developer.arm.com/-/media/Files/downloads/gnu-rm/5_3-2016q1/gccarmnoneeabi532016q120160330linuxtar.bz2?revision=417e2623-c259-4a12-aacc-c87200b569c7?product=GNU%20Arm%20Embedded%20Toolchain,32-bit,,Linux,5-2016-q1-update"
          sudo tar -jxf gcc_arm_embedded.tar.bz2
          echo "/gcc-arm-none-eabi-5_3-2016q1/bin" >> $GITHUB_PATH
          sudo pip3 install mbed-cli
          sudo pip3 install pyyaml jsonschema==2.6.0 mbed_cloud_sdk jinja2 mbed_ls mbed_host_tests mbed_greentea pyelftools manifest_tool icetea pycryptodome pyusb cmsis_pack_manager psutil cryptography click cbor prettytable==0.7.2
          mbed compile -t GCC_ARM -m NUCLEO_F446RE