name: CI
on:
    push:
        branches:
        - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install essensial
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata
          sudo apt-get install -y --no-install-recommends curl build-essential clang libboost-all-dev python3 python3-pip libc6 libncurses5 libstdc++6 wget
          wget -O gcc_arm_embedded.tar.bz2 "https://developer.arm.com/-/media/Files/downloads/gnu-rm/5_3-2016q1/gccarmnoneeabi532016q120160330linuxtar.bz2?revision=417e2623-c259-4a12-aacc-c87200b569c7?product=GNU%20Arm%20Embedded%20Toolchain,32-bit,,Linux,5-2016-q1-update"
          tar -jxf gcc_arm_embedded.tar.bz2
          echo 'export PATH="/gcc-arm-none-eabi-5_3-2016q1/bin:$PATH"' >> $BASH_ENV
      - name: Build docker image
        uses: HidetoNiwa/mbedCLI-GitHubAction-test/.github/actions/mbedCLI@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}