name: CI
on:
    push:
        branches:
        - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build docker image
        uses: HidetoNiwa/mbedCLI-GitHubAction-test/.github/actions/mbedCLI@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}